### ISSUE TITLE
Preparation for release

### ISSUE THREAD

**Issue by yasahi-hpc** [kokkos/kokkos-fft#11]
Here are the current lists from https://github.com/CExA-project/kokkos-fft/pull/8#issue-2035754983.

- [x] Add AUTHORS, who should be? Just myself for the moment (#23)
- [x] Unuse double underscore identifiers like `__KOKKOSFFT_NORMALIZATION_HPP__` (#8)
- [x] Rename `FFT_Normalization` to `Normalization` because they are already under `KokkosFFT` namespace (#8)
- [x] Add installation part to CMakeLists.txt. Also add installation test in GitHub actions (#22). Thanks a lot for your help! @cedricchevalier19 
- [x] Support transforms over odd number. The number of points for FFT direction is limited to be even number (so that the size after transform would be n/2+1) (#21)
- [x] More static assertions. Particularly, we assume that the In and Out Views have same Layout and ranks, which should be checked. (#26)
- [x] Introduce ExecSpace as a template argument as well as DDC. This allows the coexistence of fft helpers for both host and device (#12):
```
// As a template parameter
KokkosFFT::fft<Kokkos::OpenMP>(a, out); // a and out are on Host or Device is CPU
KokkosFFT::fft<Kokkos::Cuda>(a, out); // a and out are on Device

// As an argument
KokkosFFT::fft(Kokkos::OpenMP(), a, out); // a and out are on Host or Device is CPU
KokkosFFT::fft(Kokkos::Cuda(), a, out); // a and out are on Device
```
We can also make a check for memory and exec space consistency by
```
static_assert(
  Kokkos::SpaceAccessibility<ExecSpace, MemorySpace>::accessible,
  "MemorySpace has to be accessible for ExecutionSpace."
);
```
- [x] Add capability to reuse plans. This is particularly important for NVIDIA GPUs, which has some overheads to create plans (#19)
- [x] Management of default arguments. As well as numpy, I would like to allow the function calls with minimum overloading (#19)
```
KokkosFFT::fft(execution_space(), a, out);
KokkosFFT::fft(execution_space(), a, out, /*axis=*/-1);
KokkosFFT::fft(execution_space(), a, out, /*n=*/n0);
KokkosFFT::fft(execution_space(), a, out, KokkosFFT::FFT_Normalization::BACKWARD);
KokkosFFT::fft(execution_space(), a, out, KokkosFFT::FFT_Normalization::BACKWARD, /*axis=*/*-1);
KokkosFFT::fft2(execution_space(), a, out, KokkosFFT::FFT_Normalization::BACKWARD, /*axes=*/axes_type{-2, -1});
KokkosFFT::fft(execution_space(), a, out, plan, KokkosFFT::FFT_Normalization::BACKWARD, /*axis=*/-1);
```
Particularly, it is difficult to distinguish `n` and `axis`, where `n` is a `size_t` type and axis is an `int` type.
- [x] Introduce the `Impl` namespace to disallow users to access implementation details (#13)
- [x] Add missing functions such as [hfft](https://numpy.org/doc/stable/reference/generated/numpy.fft.hfft.html#numpy.fft.hfft) (#16)
- [x] Add missing helper functions such as [fftfreq](https://numpy.org/doc/stable/reference/generated/numpy.fft.fftfreq.html) (#17)
- [x] Add capability to allow optimal argument n. (See [fft](https://numpy.org/doc/stable/reference/generated/numpy.fft.fft.html#numpy.fft.fft)) (#16)
- [x] Googletest should be parameterized over types using ::testing::Types (#14)
- [x] Add docs to explain what are our interfaces and how to use them (#42)
- [x] introduce a clang format file ideally from Kokkos repo (#20)
- [x] Adding `perf_test` with `googlebenchmark` (#41)
- [x] Add capability to call KokkosFFT APIs from both host and device. This is not quite useful so I will make it optional. (#18)
```
using execution_space = Kokkos::DefaultExecutionSpace;
using host_execution_space = Kokkos::DefaultHostExecutionSpace;
KokkosFFT::fft(execution_space(), a, out); // Calling FFTs on Device
KokkosFFT::fft(host_execution_space(), h_a, h_out); // Calling FFTs on Host
```
- [x] Improve docker files and add CI on GPUs (#29)
Thanks a lot for your help! @pzehner
- [x] `Kokkos::Threads` support (#31, #46)
- [x] Adding 4D to 8D capabilities (#51)
- [x] #63

The remaining issues which may be important in the future
- [ ] #57
- [ ] #58
- [x] Add Intel GPU support based on oneMKL (#38)
- [ ] Add nvidia-hpc-sdk env. Build issue on the container (#50).
- [ ] #59
- [x] #60
- [x] #61
- [ ] #62
- [x] #65
